version: "3.9"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-seed:
    build:
      dockerfile: Dockerfile
      context: "./mongo-seed"
    depends_on:
      - mongodb

  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    environment:
      - JWT_TOKEN_SECRET=super-secret-token-here
      - NODE_ENV=development
      - PORT=3001
      - MONGO_CONN_STRING=mongodb://mongodb/malware_app

  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
